input_data_path: "data/raw/heart.csv"
output_model_path: "models/model_logreg.pkl"
output_predict_path: 'data/prediction_logreg.csv'
metric_path: "models/metrics_logreg.json"
splitting_params:
  validation_size: 0.15
  random_state: 42
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "target"
